config/routes.rb
Myapp::Application.routes.draw do

  root to: 'static#index'

  devise_for :users

  devise_scope :user do
    get 'users/new', to: 'users/registrations#new_user'
    post 'users/create_user',
        to: 'users/registrations#create_user'
    get 'user/show/:id', to: 'users/registrations#show', as: :user_show
    get 'users/index', to: 'users/registrations#index'
    get 'users/edit_user/:id', to: 'users/registrations#edit_user', as: :user_edit_user
    post 'users/update_user', to: 'users/registrations#update_user'
    delete 'users/delete_user/:id', to: 'users/registrations#delete_user', as: :user_delete_user
    get 'profile', to: 'users/profiles#profile'
    get 'profile/edit', to: 'users/profiles#edit'
    post 'profile/update', to: 'users/profiles#update'
  end

  scope module: 'users' do
    resources :mall_users
    resources :user_tiendas
  end

  resources :roles

  resources :locals

  resources :malls

  resources :nivel_malls

  resources :pais

  get 'locals' => 'locals#index', as: :local_index

  get 'locals/new' => 'locals#new'

  get 'nivel_malls/index/:mall_id' => 'nivel_malls#index', as: :nivel_malls_index

  get 'nivel_malls/new/:mall_id' => 'nivel_malls#new'

  get 'nivel_malls/test_ajax' => 'nivel_malls#test_ajax'

  get 'actividad_economicas' => 'actividad_economicas#index', as: :actividad_economicas

  get 'actividad_economica' => 'actividad_economicas#show'
  
  resources :tipo_canon_alquilers

  resources :cambio_monedas
  
  resources :actividad_economicas

  resources :calendario_no_laborables

  resources :arrendatarios

  resources :tiendas

  resources :ventas

  resources :contrato_alquilers

  get 'auditoria_ventas' => 'ventas#auditoria', as: :auditoria_ventas

  get 'ventas_tiendas/:tienda_id' => 'ventas#index', as: :ventas_tienda

  get 'ventas_mes_tiendas' => 'ventas#index', as: :ventas_mes_tienda

  get 'ventas_mall_tiendas' => 'ventas#mall_tiendas', as: :ventas_mall_tiendas

  scope module: 'dynamic' do
    post 'dynamic_add_actividad/actividad'
    post 'dynamic_venta_diaria/venta'
    post 'dynamic_venta_diaria/guardar_ventas'
    post 'dynamic_venta_auditoria/auditoria'
  end
end

app/models/calendario_no_laborable.rb
# == Schema Information
#
# Table name: calendario_no_laborables
#
#  id         :integer          not null, primary key
#  fecha      :date
#  motivo     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class CalendarioNoLaborable < ActiveRecord::Base
  validates :motivo, presence: true
  validates :fecha, presence: true, uniqueness: true

  def cantidad_dias_laborables(mes,anio)
    @mes = Time.days_in_month(mes.to_i, anio.to_i)

    @today = Time.now
    if (mes == @today.strftime("%-m") && anio == @today.strftime("%Y"))
      @mes =  @today.strftime("%d").to_i
    else
      @mes = Time.days_in_month(mes.to_i, anio.to_i)
    end

    @dias = CalendarioNoLaborable.where('extract(year from fecha) = ? AND extract(month from fecha ) = ?', anio,mes).count
    return (@mes-@dias)
  end
end

app/controllers/calendario_no_laborables_controller.rb
class CalendarioNoLaborablesController < ApplicationController
  before_action :set_calendario_no_laborable, only: [:show, :edit, :update, :destroy]

  # GET /calendario_no_laborables
  # GET /calendario_no_laborables.json
  def index
    @calendario_no_laborables = CalendarioNoLaborable.all
  end

  # GET /calendario_no_laborables/1
  # GET /calendario_no_laborables/1.json
  def show
  end

  # GET /calendario_no_laborables/new
  def new
    @calendario_no_laborable = CalendarioNoLaborable.new
  end

  # GET /calendario_no_laborables/1/edit
  def edit
  end

  # POST /calendario_no_laborables
  # POST /calendario_no_laborables.json
  def create
    @calendario_no_laborable = CalendarioNoLaborable.new(calendario_no_laborable_params)

    respond_to do |format|
      if @calendario_no_laborable.save
        format.html { redirect_to @calendario_no_laborable, notice: 'Calendario no laborable was successfully created.' }
        format.json { render :show, status: :created, location: @calendario_no_laborable }
      else
        format.html { render :new }
        format.json { render json: @calendario_no_laborable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendario_no_laborables/1
  # PATCH/PUT /calendario_no_laborables/1.json
  def update
    respond_to do |format|
      if @calendario_no_laborable.update(calendario_no_laborable_params)
        format.html { redirect_to @calendario_no_laborable, notice: 'Calendario no laborable was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendario_no_laborable }
      else
        format.html { render :edit }
        format.json { render json: @calendario_no_laborable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendario_no_laborables/1
  # DELETE /calendario_no_laborables/1.json
  def destroy
    @calendario_no_laborable.destroy
    respond_to do |format|
      format.html { redirect_to calendario_no_laborables_url, notice: 'Calendario no laborable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendario_no_laborable
      @calendario_no_laborable = CalendarioNoLaborable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendario_no_laborable_params
      params.require(:calendario_no_laborable).permit(:fecha, :motivo)
    end
end

app/views/calendario_no_laborables/_form.html.erb
<%= form_for(@calendario_no_laborable) do |f| %>
  <% if @calendario_no_laborable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendario_no_laborable.errors.count, "error") %> prohibited this calendario_no_laborable from being saved:</h2>

      <ul>
      <% @calendario_no_laborable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :motivo %><br>
    <%= f.text_field :motivo %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/calendario_no_laborables/edit.html.erb
<h1>Editando Calendario No Laborable</h1>

<%= render 'form' %>

<%= link_to 'Ver', @calendario_no_laborable %> |
<%= link_to 'Regresar', calendario_no_laborables_path %>

app/views/calendario_no_laborables/index.html.erb
<h1>Lista de Calendario No Laborables</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Motivo</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @calendario_no_laborables.each do |calendario_no_laborable| %>
      <tr>
        <td><%= calendario_no_laborable.fecha %></td>
        <td><%= calendario_no_laborable.motivo %></td>
        <td><%= link_to 'Ver', calendario_no_laborable %></td>
        <td><%= link_to 'Editar', edit_calendario_no_laborable_path(calendario_no_laborable) %></td>
        <td><%= link_to 'Eliminar', calendario_no_laborable, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Calendario No Laborable', new_calendario_no_laborable_path %>

app/views/calendario_no_laborables/new.html.erb
<h1>Nuevo Calendario No Laborable</h1>

<%= render 'form' %>

<%= link_to 'Back', calendario_no_laborables_path %>

app/views/calendario_no_laborables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @calendario_no_laborable.fecha %>
</p>

<p>
  <strong>Motivo:</strong>
  <%= @calendario_no_laborable.motivo %>
</p>

<%= link_to 'Editar', edit_calendario_no_laborable_path(@calendario_no_laborable) %> |
<%= link_to 'Regresar', calendario_no_laborables_path %>