config/routes.rb
Myapp::Application.routes.draw do

  root to: 'static#index'

  devise_for :users

  devise_scope :user do
    get 'users/new', to: 'users/registrations#new_user'
    post 'users/create_user',
        to: 'users/registrations#create_user'
    get 'user/show/:id', to: 'users/registrations#show', as: :user_show
    get 'users/index', to: 'users/registrations#index'
    get 'users/edit_user/:id', to: 'users/registrations#edit_user', as: :user_edit_user
    post 'users/update_user', to: 'users/registrations#update_user'
    delete 'users/delete_user/:id', to: 'users/registrations#delete_user', as: :user_delete_user
    get 'profile', to: 'users/profiles#profile'
    get 'profile/edit', to: 'users/profiles#edit'
    post 'profile/update', to: 'users/profiles#update'
  end

  scope module: 'users' do
    resources :mall_users
    resources :user_tiendas
  end

  resources :roles

  resources :locals

  resources :malls

  resources :nivel_malls

  resources :pais

  get 'locals' => 'locals#index', as: :local_index

  get 'locals/new' => 'locals#new'

  get 'nivel_malls/index/:mall_id' => 'nivel_malls#index', as: :nivel_malls_index

  get 'nivel_malls/new/:mall_id' => 'nivel_malls#new'

  get 'nivel_malls/test_ajax' => 'nivel_malls#test_ajax'

  get 'actividad_economicas' => 'actividad_economicas#index', as: :actividad_economicas

  get 'actividad_economica' => 'actividad_economicas#show'
  
  resources :tipo_canon_alquilers

  resources :cambio_monedas
  
  resources :actividad_economicas

  resources :calendario_no_laborables

  resources :arrendatarios

  resources :tiendas

  resources :ventas

  resources :contrato_alquilers

  get 'auditoria_ventas' => 'ventas#auditoria', as: :auditoria_ventas

  get 'ventas_tiendas/:tienda_id' => 'ventas#index', as: :ventas_tienda

  get 'ventas_mes_tiendas' => 'ventas#index', as: :ventas_mes_tienda

  get 'ventas_mall_tiendas' => 'ventas#mall_tiendas', as: :ventas_mall_tiendas

  scope module: 'dynamic' do
    post 'dynamic_add_actividad/actividad'
    post 'dynamic_venta_diaria/venta'
    post 'dynamic_venta_diaria/guardar_ventas'
    post 'dynamic_venta_auditoria/auditoria'
  end
end

app/models/contrato_alquiler.rb
# == Schema Information
#
# Table name: contrato_alquilers
#
#  id                  :integer          not null, primary key
#  nro_contrato        :string(255)
#  fecha_inicio        :date
#  fecha_fin           :date
#  archivo_contrato    :string(255)
#  canon_fijo_ml       :decimal(, )
#  canon_fijo_usd      :decimal(, )
#  porc_canon_ventas   :decimal(, )
#  monto_minimo_ventas :decimal(, )
#  estado_contrato     :boolean
#  tipo_canon_alquiler :integer
#  tienda_id           :integer
#  created_at          :datetime
#  updated_at          :datetime
#

class ContratoAlquiler < ActiveRecord::Base
  before_create :set_nro_contrato
  before_update :clean_canon_alquiler
  belongs_to :tienda
  has_one :mall, through: :tienda

  validates :tipo_canon_alquiler, :archivo_contrato, presence: true

 # mount_uploader :archivo_contrato, FileUploader

  enum tipo_canon_alquiler: [:canon_fijo, :canon_fijo_y_porcentaje_ventas, :porcentaje_de_ventas]

  def clean_canon_alquiler
    if self.tipo_canon_alquiler == "canon_fijo"
      self.porc_canon_ventas = nil
      self.monto_minimo_ventas = nil
    elsif self.tipo_canon_alquiler == "porcentaje_de_ventas"
      self.canon_fijo_ml = nil
      self.canon_fijo_usd = nil
    end
  end

  def set_nro_contrato
    self.nro_contrato = NumerosControl.get_nro_contrato
  end

  def fecha_inicio_fix
    self.fecha_inicio.strftime("%d/%m/%Y")
  end

  def fecha_fin_fix
    self.fecha_fin.strftime("%d/%m/%Y")
  end

  def archivo_contrato_pdf?
    return true if self.archivo_contrato.url.split('.').last == 'pdf'
    return false
  end
end

app/controllers/contrato_alquilers_controller.rb
class ContratoAlquilersController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_contrato_alquiler, only: [:show, :edit, :update, :destroy]
  before_action :set_tienda_aux, only: :update
  before_action :set_tienda, only: [:index, :new, :create, :destroy, :show, :edit]
  before_action :set_contrato_alquiler, only: [:destroy, :show, :edit, :update]

  # GET /contrato_alquilers
  # GET /contrato_alquilers.json
  def index
    @contrato_alquilers = @tienda.contrato_alquilers
  end

  # GET /contrato_alquilers/1
  # GET /contrato_alquilers/1.json
  def show
  end

  # GET /contrato_alquilers/new
  def new
    @contrato_alquiler = ContratoAlquiler.new
  end

  # GET /contrato_alquilers/1/edit
  def edit
  end

  # POST /contrato_alquilers
  # POST /contrato_alquilers.json
  def create
    @contrato_alquiler = @tienda.contrato_alquilers.build(contrato_alquiler_params)
    respond_to do |format|
      if @contrato_alquiler.save
        format.html { redirect_to contrato_alquilers_path(tienda: @tienda.nombre, id: @tienda.id), notice: 'Contrato de alquiler creado satisfactoriamente.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @contrato_alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contrato_alquilers/1
  # PATCH/PUT /contrato_alquilers/1.json
  def update
    respond_to do |format|
      if @contrato_alquiler.update(contrato_alquiler_params)
        format.html { redirect_to contrato_alquilers_path(tienda: @tienda.nombre, id: @tienda.id), notice: 'Contrato de alquiler actualizado satisfactoriamente.'  }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contrato_alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contrato_alquilers/1
  # DELETE /contrato_alquilers/1.json
  def destroy
    if @contrato_alquiler.mall.id == current_user.mall.id
      @contrato_alquiler.destroy
      respond_to do |format|
        format.html { redirect_to contrato_alquilers_url(tienda: @tienda.nombre, id: @tienda.id), alert: 'Se ha eliminado el contrato de alquiler'  }
        format.json { head :no_content }
      end
    end
  end

  private

    def set_tienda
      @tienda = current_user.mall.tiendas.find_by(id: ActionController::Parameters.new(id: params[:id]).permit(:id)[:id])
    end

    def set_tienda_aux
      @tienda = current_user.mall.tiendas.find_by(id: ActionController::Parameters.new(aux: params[:aux]).permit(:aux)[:aux])
    end

    def set_contrato_alquiler
      @contrato_alquiler = @tienda.contrato_alquilers.find_by(id: ActionController::Parameters.new(ca: params[:ca]).permit(:ca)[:ca])
    end

    def contrato_alquiler_params
      params.require(:contrato_alquiler).permit(:nro_contrato, :fecha_inicio, :fecha_fin, :archivo_contrato, :canon_fijo_ml, :monto_minimo_ventas, :canon_fijo_usd, :porc_canon_ventas, :estado_contrato, :tipo_canon_alquiler, :tienda_id)
    end
end

app/helpers/contrato_alquilers_helper.rb
module ContratoAlquilersHelper
end

app/views/contrato_alquilers/_contrato_vencido.html.haml
.panel.panel-danger
  .panel-heading
    %h3
      Contrato Actual Número:
      = @tienda.contrato_alquilers.last.nro_contrato
      Vencido
  .panel-body
    Su Contrato Actual esta Vencido, puede:
    = link_to "Renovar este Contrato", edit_contrato_alquiler_path(tienda: @tienda.nombre, id: @tienda.id, ca: @tienda.contrato_alquilers.last.id), class: 'btn btn-warning'
    ó
    = link_to "Registrar un Nuevo Contrato", new_contrato_alquiler_path(tienda: @tienda.nombre, id: @tienda.id), class: 'btn btn-mall'
    %br
    %br
    %p.text-danger
      %strong Fecha Fin del Contrato:
      = @tienda.contrato_alquilers.last.fecha_fin_fix
    = render 'datos_contrato'

app/views/contrato_alquilers/_contrato_vigente.html.haml
.panel.panel-success
  .panel-heading
    %h3
      Contrato Actual Número:
      = @tienda.contrato_alquilers.last.nro_contrato
  .panel-body
    = link_to "Editar Contrato", edit_contrato_alquiler_path(tienda: @tienda.nombre, id: @tienda.id, ca: @tienda.contrato_alquilers.last.id), class: 'btn btn-success'
    %br
    %br
    %p.text-success
      %strong Fecha Fin del Contrato:
      = @tienda.contrato_alquilers.last.fecha_fin_fix
    = render 'datos_contrato'

app/views/contrato_alquilers/_datos_contrato.html.haml
%p
  %strong Fecha Inicio del Contrato:
  = @tienda.contrato_alquilers.last.fecha_inicio_fix
  %p
    %strong Número de Contrato:
    = @tienda.contrato_alquilers.last.nro_contrato
  %p
    %strong Tipo de Canon de Alquiler:
    = @tienda.contrato_alquilers.last.tipo_canon_alquiler.humanize.titleize
  - if @tienda.contrato_alquilers.last.tipo_canon_alquiler == 'canon_fijo'
    %p
      %strong Monto Canón Fijo en Bs.:
      = @tienda.contrato_alquilers.last.canon_fijo_ml
    %p
      %strong Monto Canón Fijo en $:
      = @tienda.contrato_alquilers.last.canon_fijo_usd
  - elsif @tienda.contrato_alquilers.last.tipo_canon_alquiler == 'porcentaje_ventas'
    %p
      %strong Porcentaje Canón por Ventas:
      = @tienda.contrato_alquilers.last.porc_canon_ventas
    %p
      %strong Monto Mínimo Ventas Mensual:
      = @tienda.contrato_alquilers.last.monto_minimo_ventas
  - else
    %p
      %strong Monto Canón Fijo en Bs:
      = @tienda.contrato_alquilers.last.canon_fijo_ml
    %p
      %strong Monto Canón Fijo en $:
      = @tienda.contrato_alquilers.last.canon_fijo_usd
    %p
      %strong Porcentaje Canón por Ventas:
      = @tienda.contrato_alquilers.last.porc_canon_ventas
    %p
      %strong Monto Mínimo Ventas Mensual:
      = @tienda.contrato_alquilers.last.monto_minimo_ventas
  %p
    %strong Archivo Contrato;
    - if @tienda.contrato_alquilers.last.archivo_contrato_pdf?
      = link_to @tienda.contrato_alquilers.last.archivo_contrato.url.split('/').last, @tienda.contrato_alquilers.last.archivo_contrato.url
    - else
      = link_to (image_tag @tienda.contrato_alquilers.last.archivo_contrato.url,heigth: 1000, width: 200), @tienda.contrato_alquilers.last.archivo_contrato.url

app/views/contrato_alquilers/_form.html.haml
= form_for @contrato_alquiler, html: {class: 'form-horizontal m-t-md', id: 'contrato_alquiler_form'} do |f|
  = render 'shared/error_messages', object: f.object, model: 'Usuario Mall'
  = hidden_field_tag :id, @tienda.id
  = hidden_field_tag :aux, @tienda.id
  = hidden_field_tag :ca, @contrato_alquiler.id
  .form-group
    = f.label :fecha_inicio, class: 'col-sm-2 control-label' do
      Fecha Inicio del Contrato:
    .col-sm-10.form-inline
      = f.date_select :fecha_inicio,{}, class: 'form-control'
  .form-group
    = f.label :fecha_fin, class: 'col-sm-2 control-label' do
      Fecha Fin del Contrato:
    .col-sm-10.form-inline
      = f.date_select :fecha_fin, {}, class: 'form-control'
  .form-group
    = f.label :archivo_contrato, class: 'col-sm-2 control-label' do
      Contrato de Alquiler Digitalizado:
    .col-sm-10
      = render 'shared/file_upload_generic', f: f, field: :archivo_contrato, name_file: f.object.archivo_contrato || nil
  .form-group
    = f.label :tipo_canon_alquiler, class: 'col-sm-2   control-label' do
      Tipo Canon Alquiler:
    .col-sm-10
      = f.select :tipo_canon_alquiler, ContratoAlquiler.tipo_canon_alquilers.keys.to_a.map { |x| [x.humanize.titleize, x]}, {selected: f.object.tipo_canon_alquiler || nil, include_blank: 'Seleccione un Tipo de Canon de Alquiler'}, {class: 'form-control tipo_canon_alquiler_required', id: 'select_canon_alquiler'}
  %div#canon_fijo{style: (f.object.tipo_canon_alquiler == 'canon_fijo_y_porcentaje_ventas' || f.object.tipo_canon_alquiler == 'canon_fijo') ? '' : 'display:none'}
    .form-group
      = f.label :canon_fijo_ml, class: 'col-sm-2 control-label' do
        Canón Fijo en Bs.:
      .col-sm-10
        = f.text_field :canon_fijo_ml, class: 'form-control numeric_contrato_alquiler'
    .form-group
      = f.label :canon_fijo_usd, class: 'col-sm-2 control-label ' do
        Canón Fijo en $:
      .col-sm-10
        = f.text_field :canon_fijo_usd, class: 'form-control numeric_contrato_alquiler'
  %div#canon_porcentaje{style: (f.object.tipo_canon_alquiler == 'canon_fijo_y_porcentaje_ventas' || f.object.tipo_canon_alquiler == 'porcentaje_de_ventas') ? '' : 'display:none'}
    .form-group
      = f.label :porc_canon_ventas, class: 'col-sm-2 control-label' do
        \% de Canon por Ventas:
      .col-sm-10
        = f.text_field :porc_canon_ventas, class: 'form-control numeric_contrato_alquiler'
    .form-group
      = f.label :monto_minimo_ventas, class: 'col-sm-2 control-label' do
        Monto Mínimo de Ventas Mensual:
      .col-sm-10
        = f.text_field :monto_minimo_ventas, class: 'form-control numeric_contrato_alquiler'
  .form-group
    .col-sm-3
      = link_to 'Atras', contrato_alquilers_path(tienda: @tienda.nombre, id: @tienda.id), class: 'btn btn-warning btn-block'
    .col-sm-3.col-sm-offset-6
      = f.submit 'Guardar', class: 'btn btn-mall btn-block'

app/views/contrato_alquilers/edit.html.haml
= provide(:title, "#{@tienda.mall.nombre } - #{@tienda.nombre} - Contratos Alquiler")
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      = current_user.mall.nombre
      \- Edicion Contrato de Alquiler Número:
      = @contrato_alquiler.nro_contrato
      \-
      = @tienda.nombre
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        = link_to 'Tiendas', tiendas_path
      %li
        = link_to "#{@tienda.nombre} Contratos Alquiler", contrato_alquilers_path(tienda: @tienda.nombre, id: @tienda.id)
      %li
        Edición de Contrato
        = @tienda.nombre

.wrapper.wrapper-content
  .row.animated.fadeInRight
    .col-md-12
      .ibox.float-e-margins
        .ibox-title
          %h3
            = current_user.mall.nombre
            \-
            = @tienda.nombre
            \-
            Edición de Contrato de Alquiler
        = render 'form'

app/views/contrato_alquilers/index.html.haml
= provide(:title, "#{@tienda.mall.nombre } - #{@tienda.nombre} - Contratos Alquiler")
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      = current_user.mall.nombre
      \- Contratos de Alquiler
      = @tienda.nombre
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        = link_to 'Tiendas', tiendas_path
      %li
        Contratos de Alquiler
        = @tienda.nombre
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          %h2
            = @tienda.nombre
          -#%br
          -#%br
          -#.row
          -#  .col-sm-3
          -#    = link_to "Renovar Contrato - #{@tienda.nombre}", new_contrato_alquiler_path(tienda: @tienda.nombre, id: @tienda.id), class: 'btn btn-mall'
          %br
          .row
            .col-sm-12
              - if @tienda.contrato_alquilers.last.fecha_fin > Date.today
                = render 'contrato_alquilers/contrato_vigente'
              - else
                = render 'contrato_alquilers/contrato_vencido'
          .row
            .col-md-12
              %h3
                Histórico de Contratos -
                = @tienda.nombre
          .row
            .col-md-12
              %table.table.table-striped.table-bordered.table-hover
                %thead
                  %tr
                    %th Número contrato
                    %th Fecha de inicio
                    %th Fecha fin
                    %th Tipo de Canón de Alquiler
                    %th Monto Canón Fijo en Bs.
                    %th Monto Canón Fijo en $.
                    %th % Canón por Ventas
                    %th Monto Mínimo Ventas Mensual
                    %th Estado contrato
                    %th Archivo contrato
                    %th Acciones
                %tbody
                  - @contrato_alquilers.each do |contrato_alquiler|
                    %tr
                      %td= contrato_alquiler.nro_contrato
                      %td= contrato_alquiler.fecha_inicio_fix
                      %td= contrato_alquiler.fecha_fin_fix
                      %td= contrato_alquiler.tipo_canon_alquiler.humanize.capitalize
                      %td= contrato_alquiler.canon_fijo_ml
                      %td= contrato_alquiler.canon_fijo_usd
                      %td= contrato_alquiler.porc_canon_ventas
                      %td= contrato_alquiler.monto_minimo_ventas
                      %td= contrato_alquiler.estado_contrato
                      %td
                        - if contrato_alquiler.archivo_contrato_pdf?
                          = link_to contrato_alquiler.archivo_contrato.url.split('/').last, contrato_alquiler.archivo_contrato.url
                        - else
                          = link_to (image_tag contrato_alquiler.archivo_contrato.url,heigth: 1000, width: 80), contrato_alquiler.archivo_contrato.url
                      %td
                        = link_to  contrato_alquiler_path(id: @tienda.id, ca: contrato_alquiler.id), method: :delete, data: { confirm: "¿Esta seguro que desea eliminar el contrato nro: #{contrato_alquiler.nro_contrato} de la tienda #{@tienda.nombre}?" } do
                          %i.fa.fa-trash

app/views/contrato_alquilers/new.html.haml
= provide(:title, "#{@tienda.mall.nombre } - #{@tienda.nombre} - Contratos Alquiler")
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      = current_user.mall.nombre
      \- Nuevo Contrato de Alquiler -
      = @tienda.nombre
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        = link_to 'Tiendas', tiendas_path
      %li
        = link_to "#{@tienda.nombre} Contratos Alquiler", contrato_alquilers_path(tienda: @tienda.nombre, id: @tienda.id)
      %li
        Nuevo Contrato Alquiler
        = @tienda.nombre

.wrapper.wrapper-content
  .row.animated.fadeInRight
    .col-md-12
      .ibox.float-e-margins
        .ibox-title
          %h3
            = current_user.mall.nombre
            \-
            = @tienda.nombre
            \-
            Renovación de Contrato de Alquiler
        = render 'form'

app/views/contrato_alquilers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nro contrato:</strong>
  <%= @contrato_alquiler.nro_contrato %>
</p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @contrato_alquiler.fecha_inicio %>
</p>

<p>
  <strong>Fecha fin:</strong>
  <%= @contrato_alquiler.fecha_fin %>
</p>

<p>
  <strong>Archivo contrato:</strong>
  <%= @contrato_alquiler.archivo_contrato %>
</p>

<p>
  <strong>Canon fijo ml:</strong>
  <%= @contrato_alquiler.canon_fijo_ml %>
</p>

<p>
  <strong>Canon fijo usd:</strong>
  <%= @contrato_alquiler.canon_fijo_usd %>
</p>

<p>
  <strong>Porc canon ventas:</strong>
  <%= @contrato_alquiler.porc_canon_ventas %>
</p>

<p>
  <strong>Estado contrato:</strong>
  <%= @contrato_alquiler.estado_contrato %>
</p>

<p>
  <strong>Tipo canon alquiler:</strong>
  <%= @contrato_alquiler.tipo_canon_alquiler %>
</p>

<p>
  <strong>Tienda:</strong>
  <%= @contrato_alquiler.tienda %>
</p>

<%= link_to 'Edit', edit_contrato_alquiler_path(@contrato_alquiler) %> |
<%= link_to 'Back', contrato_alquilers_path %>